INSERT INTO "EVALUACION3"."CURSO" (IDCURSO, IDPROGRAMA) VALUES ('1', '1');
INSERT INTO "EVALUACION3"."CURSO" (IDCURSO, IDPROGRAMA) VALUES ('2', '1');
INSERT INTO "EVALUACION3"."CURSO" (IDCURSO, IDPROGRAMA) VALUES ('3', '2');
INSERT INTO "EVALUACION3"."CURSO" (IDCURSO, IDPROGRAMA) VALUES ('4', '2');
INSERT INTO "EVALUACION3"."CURSO" (IDCURSO, IDPROGRAMA) VALUES ('5', '3');
INSERT INTO "EVALUACION3"."CURSO" (IDCURSO, IDPROGRAMA) VALUES ('6', '3');



