INSERT INTO "EVALUACION3"."PROGRAMA" (IDPROGRAMA, NOMBRE) VALUES ('1', 'Full Stack Java Trainee');
INSERT INTO "EVALUACION3"."PROGRAMA" (IDPROGRAMA, NOMBRE) VALUES ('2', 'Programacion Android');
INSERT INTO "EVALUACION3"."PROGRAMA" (IDPROGRAMA, NOMBRE) VALUES ('3', 'Desarrollador Videojuegos');